project_id = "dmarkaigzovaqwpigtxe"

[functions.guest-submit]
verify_jwt = false

[functions.guest-verify]
verify_jwt = false

[functions.get-push-config]
verify_jwt = false

[functions.blockchain-verify]
verify_jwt = true

[functions.notify-users]
verify_jwt = false

[functions.create-razorpay-order]
verify_jwt = true

[functions.verify-razorpay-payment]
verify_jwt = true

[functions.create-donation-order]
verify_jwt = false

[functions.verify-donation-payment]
verify_jwt = false
